# The below code is generated by Gemeni, for my own convinience :)

import re
import os

# --- CONFIGURE THIS ---
START_DIRECTORY = "./src/content/studies"  # Change this to your notes directory
# ----------------------

# The regex:
# (?s)       = "dotall" flag, makes "." match newlines
# \$\$       = literal $$
# (.*?)      = capture group 1: non-greedy match of EVERYTHING
# \$\$       = literal $$
pattern = re.compile(r"(?s)\$\$(.*?)\$\$")

# The replacement:
# \n$$       = newline and $$
# \1         = the captured group (your math)
# $$\n       = $$ and a newline
# We add extra newlines to be safe.
replacement = r"\n$$\n\1\n$$\n"

file_count = 0

# Walk through all files and subdirectories
for dirpath, dirnames, filenames in os.walk(START_DIRECTORY):
    for filename in filenames:
        if filename.endswith(".md"):
            file_path = os.path.join(dirpath, filename)
            
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                # Check if there are any matches at all
                if pattern.search(content):
                    print(f"--- Fixing {file_path} ---")
                    
                    # Run the replacement
                    # We add newlines *around* the replacement to be safe
                    new_content = pattern.sub(replacement, content)
                    
                    # A simple clean-up to prevent massive gaps
                    # This turns 3+ newlines into just two
                    new_content = re.sub(r"\n{3,}", "\n\n", new_content)

                    # Write the new content back to the file
                    with open(file_path, 'w', encoding='utf-8') as f:
                        f.write(new_content)
                    
                    file_count += 1
                
            except Exception as e:
                print(f"Could not process {file_path}: {e}")

print(f"\nDone. Fixed {file_count} files.")
